// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config"
import { defineConfig } from "prisma/config"

const defaultDatabaseUrl = "postgresql://postgres:password@localhost:5432/dissertation_db?schema=public"

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: { path: "prisma/migrations" },
  datasource: {
    url: process.env.DATABASE_URL || defaultDatabaseUrl,
  },
})
